### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by CozmoDev** [AiekDev/Pyska-API#1]
whats the purpose of it being "open source" if you aren't releasing full source? the shit in this repo is like real barebones

**Comment by AiekDev** [comment]
skids + the main bot is also hella bare bones too, it got like 12 commands that just post links/images

**Comment by AiekDev** [comment]
well yeah reason why it has like a license and shit

think of it as chromium and google chrome : chromium is just the base and google chrome uses the base of chromium + extra features

the other half of the bot is really useless and shit thats the reason why i didnt add the rest of the commands (which were hella useless pretty much)

**Comment by AiekDev** [comment]
btw i made it fully open source if u check it rn
