### ISSUE TITLE
Repeating, illogical code comments and no project structure

### ISSUE THREAD

**Issue by DevLisuu** [AiekDev/Pyska-API#4]
I would suggest going forward splitting the code into multiple files and packages instead of putting around 10 lines of the same comment just to split the code into parts, e.g.
https://github.com/AiekDev/Pyska-API/blob/e412460fd685621f52d9ccbf763a0767a263fde4/main.py#L94C1-L103C25

Also there are some occurrences of comments that just explain exactly what one method used above does like
https://github.com/AiekDev/Pyska-API/blob/e412460fd685621f52d9ccbf763a0767a263fde4/main.py#L80C53-L80C53
or comments that literally just give basic advice (to I guess future contributors), e.g.
https://github.com/AiekDev/Pyska-API/blob/e412460fd685621f52d9ccbf763a0767a263fde4/main.py#L19C7-L19C7

Those are just some of my personal thoughts and tips for a fellow new github user.

**Comment by AiekDev** [comment]
i mean its some useless discord bot (idrc about it tbh)
